
import { v4 as uuidv4 } from 'uuid';

export type DiagramType = 'neural-network' | 'flowchart' | 'timeline' | 'cycle' | 'comparison' | 'funnel' | 'mindmap' | 'venn' | 'chart' | 'concept-map';

export const DOMAIN_COLORS: Record<string, string> = {
    'Culinary': '#E07A5F',       // Terracotta
    'Nature': '#81B29A',         // Sage
    'Architecture': '#3D405B',   // Slate
    'Music': '#F2CC8F',          // Gold
    'Sports': '#E36414',         // Orange
    'Gardening': '#606C38',      // Olive
    'Travel': '#457B9D',         // Cerulean
    'Craftsmanship': '#BC6C25'   // Amber
};

interface DiagramConfig {
    title: string;
    domain?: string;
    colors?: string[]; // Fallback
    data?: any;
}

export class DiagramGenerator {

    /**
     * Main entry point to generate a diagram SVG string.
     */
    async generate(type: DiagramType, config: DiagramConfig): Promise<string> {
        const domainColor = config.domain && DOMAIN_COLORS[config.domain] ? DOMAIN_COLORS[config.domain] : (config.colors?.[0] || '#22d3ee');
        
        // Base SVG wrapper
        const width = 1200;
        const height = 800;
        const bg = '#0f172a';
        
        const svgHeader = `<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg" style="background: ${bg}; border-radius: 12px; font-family: 'Inter', sans-serif;">
            <defs>
                <filter id="glow">
                    <feGaussianBlur stdDeviation="2.5" result="coloredBlur"/>
                    <feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge>
                </filter>
                <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
                    <path d="M 40 0 L 0 0 0 40" fill="none" stroke="rgba(255,255,255,0.03)" stroke-width="1"/>
                </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#grid)" />
            <text x="${width / 2}" y="60" text-anchor="middle" font-size="32" fill="white" font-weight="bold">${this.escapeXml(config.title)}</text>`;
        
        const svgFooter = `
            <text x="40" y="${height - 40}" font-family="monospace" font-size="12" fill="#475569">Generated by AI Bytes Engine • Domain: ${config.domain || 'Generic'}</text>
        </svg>`;

        let shapes = '';
        
        switch (type) {
            case 'neural-network':
                return this.generateNeuralNetwork(config, domainColor);
            case 'flowchart':
                shapes = this.drawFlowchart(domainColor);
                break;
            case 'timeline':
                shapes = this.drawTimeline(domainColor);
                break;
            case 'cycle':
                shapes = this.drawCycle(domainColor);
                break;
            case 'comparison':
                shapes = this.drawComparison(domainColor);
                break;
            case 'funnel':
                shapes = this.drawFunnel(domainColor);
                break;
            case 'mindmap':
                shapes = this.drawMindmap(domainColor);
                break;
            case 'venn':
                shapes = this.drawVenn(domainColor);
                break;
            default:
                shapes = `<rect x="${width/2 - 150}" y="${height/2 - 100}" width="300" height="200" rx="10" fill="none" stroke="${domainColor}" stroke-width="4" stroke-dasharray="10,10"/>
                          <text x="${width/2}" y="${height/2}" text-anchor="middle" fill="#94a3b8" font-size="24">Diagram type: ${type}</text>`;
        }

        return svgHeader + shapes + svgFooter;
    }

    private escapeXml(unsafe: string): string {
        return unsafe.replace(/[<>&'"]/g, (c) => {
            switch (c) {
                case '<': return '&lt;';
                case '>': return '&gt;';
                case '&': return '&amp;';
                case '\'': return '&apos;';
                case '"': return '&quot;';
                default: return c;
            }
        });
    }

    private drawFlowchart(color: string) {
        return `
            <g transform="translate(100, 200)">
                <rect x="0" y="0" width="200" height="100" rx="8" fill="#1e293b" stroke="${color}" stroke-width="3" />
                <path d="M 200 50 L 350 50" stroke="${color}" stroke-width="3" fill="none" marker-end="url(#arrow)"/>
                <rect x="350" y="-50" width="200" height="100" rx="8" fill="#1e293b" stroke="${color}" stroke-width="3" />
                <path d="M 550 0 L 700 50" stroke="${color}" stroke-width="3" fill="none"/>
                <rect x="350" y="100" width="200" height="100" rx="8" fill="#1e293b" stroke="${color}" stroke-width="3" />
                <path d="M 550 150 L 700 50" stroke="${color}" stroke-width="3" fill="none"/>
                <rect x="700" y="0" width="200" height="100" rx="8" fill="#1e293b" stroke="${color}" stroke-width="3" />
            </g>
        `;
    }

    private drawTimeline(color: string) {
        let svg = `<line x1="100" y1="400" x2="1100" y2="400" stroke="${color}" stroke-width="6" opacity="0.5"/>`;
        for (let i = 0; i < 5; i++) {
            const x = 200 + i * 200;
            const yOffset = i % 2 === 0 ? -80 : 80;
            svg += `<circle cx="${x}" cy="400" r="16" fill="${color}" stroke="#0f172a" stroke-width="4"/>`;
            svg += `<line x1="${x}" y1="400" x2="${x}" y2="${400 + yOffset}" stroke="${color}" stroke-width="3" stroke-dasharray="5,5"/>`;
            svg += `<rect x="${x - 75}" y="${400 + yOffset + (i % 2 === 0 ? -60 : 20)}" width="150" height="40" rx="4" fill="#1e293b" stroke="${color}" stroke-width="1"/>`;
        }
        return svg;
    }

    private drawCycle(color: string) {
        return `
            <g transform="translate(600, 450)">
                <circle cx="0" cy="0" r="250" fill="none" stroke="${color}" stroke-width="6" stroke-dasharray="80, 20" opacity="0.3">
                    <animateTransform attributeName="transform" type="rotate" from="0" to="360" dur="20s" repeatCount="indefinite"/>
                </circle>
                <circle cx="0" cy="-250" r="40" fill="${color}" />
                <circle cx="216" cy="125" r="40" fill="${color}" />
                <circle cx="-216" cy="125" r="40" fill="${color}" />
            </g>
        `;
    }

    private drawComparison(color: string) {
        return `
            <line x1="600" y1="200" x2="600" y2="700" stroke="#334155" stroke-width="4" stroke-dasharray="10,10"/>
            <rect x="250" y="250" width="250" height="150" rx="10" fill="#1e293b" stroke="#334155" stroke-width="2"/>
            <rect x="700" y="250" width="250" height="150" rx="10" fill="#1e293b" stroke="${color}" stroke-width="4"/>
            <rect x="250" y="450" width="250" height="150" rx="10" fill="#1e293b" stroke="#334155" stroke-width="2"/>
            <rect x="700" y="450" width="250" height="150" rx="10" fill="#1e293b" stroke="${color}" stroke-width="4"/>
        `;
    }
    
    private drawFunnel(color: string) {
        return `
            <g transform="translate(400, 200)">
                <polygon points="0,0 400,0 250,300 150,300" fill="${color}" opacity="0.2" stroke="${color}" stroke-width="4"/>
                <polygon points="30,60 370,60 270,260 130,260" fill="${color}" opacity="0.4"/>
                <polygon points="80,160 320,160 240,240 160,240" fill="${color}" opacity="0.6"/>
                <rect x="150" y="300" width="100" height="150" rx="5" fill="${color}" />
            </g>
        `;
    }

    private drawMindmap(color: string) {
        return `
            <g transform="translate(600, 450)">
                <circle cx="0" cy="0" r="80" fill="#1e293b" stroke="${color}" stroke-width="5" />
                
                <line x1="0" y1="-80" x2="-150" y2="-200" stroke="${color}" stroke-width="3" />
                <circle cx="-150" cy="-200" r="40" fill="${color}" opacity="0.8" />
                
                <line x1="0" y1="-80" x2="150" y2="-200" stroke="${color}" stroke-width="3" />
                <circle cx="150" cy="-200" r="40" fill="${color}" opacity="0.8" />
                
                <line x1="-80" y1="0" x2="-250" y2="50" stroke="${color}" stroke-width="3" />
                <circle cx="-250" cy="50" r="40" fill="${color}" opacity="0.8" />
                
                <line x1="80" y1="0" x2="250" y2="50" stroke="${color}" stroke-width="3" />
                <circle cx="250" cy="50" r="40" fill="${color}" opacity="0.8" />
            </g>
        `;
    }

    private drawVenn(color: string) {
        return `
            <g transform="translate(600, 450)">
                <circle cx="-100" cy="0" r="200" fill="${color}" opacity="0.4" style="mix-blend-mode: screen;" />
                <circle cx="100" cy="0" r="200" fill="#475569" opacity="0.4" style="mix-blend-mode: screen;" />
                <text x="0" y="0" text-anchor="middle" fill="white" font-size="24" font-weight="bold">Overlap</text>
            </g>
        `;
    }

    private generateNeuralNetwork(config: DiagramConfig, color: string): string {
        const width = 1200;
        const height = 800;
        const layers = config.data?.layers || [4, 6, 6, 4, 2]; // Default topology

        // Calculate geometry
        const maxNodes = Math.max(...layers);
        const layerSpacing = (width - 200) / (layers.length - 1);
        const nodeSpacing = (height - 200) / maxNodes;

        let svgContent = '';
        let connections = '';
        let nodes = '';

        // Generate Nodes and Connections
        layers.forEach((nodeCount: number, layerIndex: number) => {
            const x = 100 + layerIndex * layerSpacing;
            const currentLayerNodes = [];

            // Center nodes vertically
            const startY = (height - (nodeCount * nodeSpacing)) / 2 + (nodeSpacing / 2);

            for (let i = 0; i < nodeCount; i++) {
                const y = startY + i * nodeSpacing;
                currentLayerNodes.push({ x, y });

                // Nodes
                nodes += `
                    <g class="node-group" opacity="0" transform="translate(0, 50)">
                        <circle cx="${x}" cy="${y}" r="8" fill="#0f172a" stroke="${color}" stroke-width="3" />
                        <circle cx="${x}" cy="${y}" r="4" fill="${color}">
                            <animate attributeName="opacity" values="0.5;1;0.5" dur="3s" repeatCount="indefinite" begin="${Math.random()}s"/>
                        </circle>
                        <animateTransform attributeName="transform" type="translate" to="0,0" dur="0.8s" fill="freeze" begin="${layerIndex * 0.2}s" calcMode="spline" keySplines="0.4 0 0.2 1"/>
                        <animate attributeName="opacity" to="1" dur="0.8s" fill="freeze" begin="${layerIndex * 0.2}s"/>
                    </g>
                `;
            }

            // Connections to previous layer
            if (layerIndex > 0) {
                const prevLayerCount = layers[layerIndex - 1];
                const prevLayerX = 100 + (layerIndex - 1) * layerSpacing;
                const prevStartY = (height - (prevLayerCount * nodeSpacing)) / 2 + (nodeSpacing / 2);

                for (let i = 0; i < nodeCount; i++) {
                    const y = startY + i * nodeSpacing;

                    for (let j = 0; j < prevLayerCount; j++) {
                        const prevY = prevStartY + j * nodeSpacing;
                        if (Math.random() > 0.3 || layers.length < 5) {
                            connections += `
                                <path d="M ${prevLayerX} ${prevY} C ${prevLayerX + layerSpacing * 0.5} ${prevY}, ${x - layerSpacing * 0.5} ${y}, ${x} ${y}" 
                                      stroke="${color}" stroke-width="1" opacity="0.15" fill="none">
                                      <animate attributeName="stroke-dasharray" from="0, 1000" to="1000, 0" dur="2s" fill="freeze" begin="${layerIndex * 0.15}s"/>
                                </path>
                            `;
                        }
                    }
                }
            }
        });

        return `
        <svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg" style="background: #0f172a; border-radius: 12px; font-family: 'Inter', sans-serif;">
            <defs>
                <filter id="glow">
                    <feGaussianBlur stdDeviation="2.5" result="coloredBlur"/>
                    <feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge>
                </filter>
                <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
                    <path d="M 40 0 L 0 0 0 40" fill="none" stroke="rgba(255,255,255,0.03)" stroke-width="1"/>
                </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#grid)" />
            <text x="${width / 2}" y="60" text-anchor="middle" font-size="32" fill="white" font-weight="bold">${this.escapeXml(config.title)}</text>
            <g filter="url(#glow)">${connections}${nodes}</g>
            <text x="40" y="${height - 40}" font-family="monospace" font-size="12" fill="#475569">Generated by AI Bytes Engine • Domain: ${config.domain || 'Generic'}</text>
        </svg>
        `.trim();
    }
}

// Singleton export
export const diagramGenerator = new DiagramGenerator();
