/**
 * MARP Slide Generation Prompt — AI Bytes Learning
 *
 * Architecture:
 *   - CSS and front matter are injected by the generator (NOT generated by the model)
 *   - The model generates ONLY slide content blocks separated by `---`
 *   - The generator prepends the locked front matter before saving
 *
 * Visual contract:
 *   - Light theme (#F8FAFC background) — print-safe
 *   - Syne 800 headings, Inter 400/500/600 body, JetBrains Mono code
 *   - Teal (#00C896) primary accent throughout
 *   - Navy (#0A1628) all headings and dark text
 *   - Slide ratio: 16:9
 */

// ─── Locked CSS (injected into front matter style block) ──────────────────────
// LOGO_BASE64_PLACEHOLDER is replaced by the generator with the actual base64 SVG.
export const MARP_CSS = `
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=Inter:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');

/* ── Print / Chromium page reset ── */
@page {
  margin: 0;
  padding: 0;
  border: none;
}

/* ── MARP default reset — must come first ── */
section {
  border: none !important;
  outline: none !important;
  box-shadow: none !important;
}

/* ── Base slide ── */
section {
  background: #F8FAFC;
  color: #334155;
  font-family: 'Inter', Arial, sans-serif;
  font-size: 18px;
  line-height: 1.6;
  padding: 56px 72px 80px;
  position: relative;
  box-sizing: border-box;
  border: none;
  outline: none;
  box-shadow: none;
}

/* ── Headings ── */
h1 {
  font-family: 'Syne', 'Arial Black', Arial, sans-serif;
  font-weight: 800;
  font-size: 42px;
  color: #0A1628;
  line-height: 1.12;
  letter-spacing: -0.5px;
  margin: 0 0 20px;
  padding: 0;
  border: none;
}

h2 {
  font-family: 'Syne', 'Arial Black', Arial, sans-serif;
  font-weight: 700;
  font-size: 28px;
  color: #0A1628;
  line-height: 1.2;
  border-left: 4px solid #00C896;
  padding-left: 16px;
  margin: 0 0 28px;
}

h3 {
  font-family: 'Inter', Arial, sans-serif;
  font-weight: 600;
  font-size: 12px;
  color: #00C896;
  text-transform: uppercase;
  letter-spacing: 3px;
  margin: 0 0 10px;
  padding: 0;
  border: none;
}

p {
  font-size: 18px;
  line-height: 1.65;
  color: #334155;
  margin: 0 0 16px;
}

strong {
  color: #0A1628;
  font-weight: 600;
}

em {
  color: #00C896;
  font-style: normal;
  font-weight: 500;
}

/* ── Lists ── */
ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

ul li {
  position: relative;
  padding-left: 26px;
  margin-bottom: 16px;
  font-size: 18px;
  line-height: 1.5;
  color: #334155;
}

ul li::before {
  content: '›';
  position: absolute;
  left: 0;
  top: -1px;
  color: #00C896;
  font-size: 24px;
  font-weight: 700;
  line-height: 1.3;
}

ul li strong {
  color: #0A1628;
}

/* ── Code ── */
pre {
  background: #0A1628;
  color: #E2E8F0;
  border-left: 4px solid #00C896;
  border-radius: 0 8px 8px 0;
  padding: 20px 24px;
  font-family: 'JetBrains Mono', Consolas, monospace;
  font-size: 14px;
  line-height: 1.65;
  margin: 0;
  overflow: hidden;
}

code {
  font-family: 'JetBrains Mono', Consolas, monospace;
  font-size: 14px;
  background: #E2E8F0;
  color: #0A1628;
  padding: 2px 7px;
  border-radius: 4px;
}

pre code {
  background: none;
  color: #E2E8F0;
  padding: 0;
  border-radius: 0;
  font-size: 14px;
}

/* ── Blockquote — Tip callout (default) ── */
blockquote {
  border: none;
  border-left: 5px solid #00C896;
  background: #F0FDF9;
  padding: 22px 28px;
  border-radius: 0 10px 10px 0;
  margin: 0;
}

blockquote p {
  color: #0A1628;
  font-size: 17px;
  margin: 0;
  line-height: 1.55;
}

blockquote strong {
  display: block;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 2px;
  color: #00C896;
  margin-bottom: 8px;
}

/* ── Table ── */
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 16px;
  margin: 0;
}

th {
  background: #0A1628;
  color: #FFFFFF;
  padding: 11px 16px;
  text-align: left;
  font-family: 'Inter', Arial, sans-serif;
  font-weight: 600;
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.8px;
  border: none;
}

td {
  padding: 11px 16px;
  border-bottom: 1px solid #E2E8F0;
  color: #334155;
  font-size: 16px;
}

tr:nth-child(even) td {
  background: rgba(0, 200, 150, 0.04);
}

/* ── Footer (logo) ── */
/* Logo is Teal_logo_ai-bytes-learning.png — 1080×1080 canvas, logo centred.
   background-size: auto 310px scales the full canvas so the logo mark appears ~34px tall.
   background-position: right -75px center offsets so the logo mark sits near the right edge.
   The footer height clips the canvas to the middle 52px, which is where the logo sits. */
footer {
  background-image: url('LOGO_PATH_PLACEHOLDER');
  background-repeat: no-repeat;
  background-position: right -75px center;
  background-size: auto 310px;
  height: 52px;
  border: none;
  padding: 0;
  overflow: hidden;
  bottom: 10px;
}

/* ── Page number — centred ── */
section::after {
  font-family: 'Inter', Arial, sans-serif;
  font-size: 12px;
  color: #94A3B8;
  position: absolute;
  bottom: 18px;
  left: 50%;
  transform: translateX(-50%);
  right: auto;
}

/* ─────────────────────────────────────────────
   SLIDE TYPES
   ───────────────────────────────────────────── */

/* ── COVER ── */
section.cover {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 56px 96px 72px;
  background: #F8FAFC;
}

section.cover h1 {
  font-size: 50px;
  letter-spacing: -1.5px;
  max-width: 840px;
  margin: 20px 0 18px;
}

section.cover h3 {
  font-size: 11px;
  letter-spacing: 3px;
  color: #475569;
  margin-bottom: 0;
}

section.cover p {
  font-size: 17px;
  color: #475569;
  max-width: 600px;
  margin: 0 auto;
}

section.cover::after {
  display: none;
}

section.cover footer {
  display: none;
}

/* ── DIVIDER (chapter break) ── */
section.divider {
  background: linear-gradient(90deg, #00C896 220px, #F8FAFC 220px);
  padding: 56px 72px 56px 268px;
  display: flex;
  flex-direction: column;
  justify-content: center;
}

section.divider h3 {
  color: #0A1628;
  margin-bottom: 16px;
}

section.divider h2 {
  border: none;
  padding: 0;
  font-size: 36px;
  letter-spacing: -0.5px;
  margin-bottom: 20px;
}

section.divider p {
  font-size: 17px;
  color: #475569;
  max-width: 520px;
}

section.divider::after {
  display: none;
}

section.divider footer {
  background-position: right 24px bottom 18px;
}

/* ── ANCHOR (reinforcement slide — slight tint) ── */
section.anchor {
  background: #F0FDF9;
}

section.anchor h2 {
  border-left-color: #00B383;
}

/* ── QUIZ (knowledge check) ── */
section.quiz {
  background: #F8FAFC;
}

section.quiz h3 {
  color: #9B8FFF;
  letter-spacing: 3px;
}

section.quiz h2 {
  border-left-color: #9B8FFF;
}

section.quiz table td {
  font-size: 17px;
  padding: 14px 18px;
  border: 1px solid #E2E8F0;
  border-radius: 6px;
}

section.quiz table th {
  display: none;
}

/* ── ANSWER (knowledge check answer) ── */
section.answer h3 {
  color: #00C896;
}

section.answer h2 {
  border-left-color: #00C896;
}

section.answer blockquote {
  border-left-color: #00C896;
  background: #F0FDF9;
}

/* ── WARNING callout variant ── */
section.warning blockquote {
  border-left-color: #FFB347;
  background: #FFFBEB;
}

section.warning blockquote strong {
  color: #D97706;
}

/* ── IMPORTANT callout variant ── */
section.important blockquote {
  border-left-color: #9B8FFF;
  background: #F5F3FF;
}

section.important blockquote strong {
  color: #7C3AED;
}

/* ── BACK COVER ── */
section.backcover {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 56px 96px;
  background: #F8FAFC;
}

section.backcover h2 {
  border: none;
  padding: 0;
  font-size: 30px;
  text-align: center;
  margin-bottom: 14px;
}

section.backcover p {
  color: #475569;
  font-size: 17px;
  margin-bottom: 8px;
}

section.backcover hr {
  border: none;
  border-top: 1px solid #E2E8F0;
  width: 100%;
  margin: 28px 0;
}

section.backcover::after {
  display: none;
}

section.backcover footer {
  display: none;
}
`.trim();

// ─── Front matter builder ──────────────────────────────────────────────────────
// logoFileUrl: a file:// URL pointing to the logo PNG on disk.
// marp-cli is invoked with --allow-local-files so the path resolves in Chromium.
export function buildMarpFrontMatter(logoFileUrl: string): string {
  const css = MARP_CSS.replace('LOGO_PATH_PLACEHOLDER', logoFileUrl);
  const indentedCss = css.split('\n').map(line => `  ${line}`).join('\n');
  return `---
marp: true
paginate: true
size: 16:9
footer: ' '
html: true
style: |
${indentedCss}
---`;
}

// ─── Slide generation prompt ───────────────────────────────────────────────────
// The model generates ONLY the slide content (everything after the front matter).
// The generator prepends the locked front matter before saving.

interface MarpPromptInput {
  courseTitle: string;
  courseDescription: string;
  category: string;
  difficulty: string;
  topics: Array<{
    title: string;
    description: string;
    position: number;
    lessons: Array<{
      title: string;
      contentSummary: string;
      position: number;
      imageUrl: string | null;
    }>;
    quizQuestion?: {
      question: string;
      options: string[];
      correctIndex: number;
      explanation: string;
    };
    keyTerms?: Array<{ term: string; definition: string }>;
  }>;
  totalTopics: number;
  estimatedMinutes: number;
  totalXp: number;
}

export function getMarpSlidesPrompt(input: MarpPromptInput): string {
  const topicsJson = JSON.stringify(input.topics, null, 2);

  return `You are generating a MARP presentation slide deck for AI Bytes Learning.

OUTPUT RULES — READ THESE FIRST:
- Output ONLY raw MARP markdown. No code fences. No preamble. No explanation.
- Start immediately with the cover slide (first line must be a MARP class comment or heading).
- Slides are separated by a line containing only: ---
- Use EXACTLY the slide structure and class names specified below.
- No emojis anywhere in the output.
- No inline HTML anywhere in the output.
- No inline CSS anywhere in the output.
- UK English spelling throughout.

COURSE DATA:
Title: ${input.courseTitle}
Description: ${input.courseDescription}
Category: ${input.category}
Difficulty: ${input.difficulty}
Topics: ${input.totalTopics}
Estimated time: ${input.estimatedMinutes} minutes
XP available: ${input.totalXp}

TOPIC AND LESSON DATA:
${topicsJson}

════════════════════════════════════════════════════════
EXACT SLIDE STRUCTURE — FOLLOW WITHOUT DEVIATION
════════════════════════════════════════════════════════

SLIDE 1 — COVER (one per deck)
───────────────────────────────
<!-- _class: cover -->
<!-- _paginate: false -->

### [CATEGORY] · [DIFFICULTY]

# [Course Title]

[One sentence: what the student will be able to do after this course. Max 15 words. Start with a verb.]

═══════════════════════════════════════
REPEAT THE FOLLOWING FOR EACH TOPIC:
═══════════════════════════════════════

SLIDE — TOPIC DIVIDER (one per topic)
───────────────────────────────────────
<!-- _class: divider -->
<!-- _paginate: false -->

### TOPIC [N] OF [TOTAL]

## [Topic Title]

[Topic description. One sentence. Max 20 words. What shifts in the student's understanding after this topic.]

THEN FOR EACH LESSON IN THE TOPIC — ONE SLIDE ONLY:

SLIDE — LESSON (one per lesson, no exceptions)
────────────────────────────────────────────────
If the lesson has a non-null imageUrl in the topic data, add this as the VERY FIRST line of the slide (before any heading):
![bg right:38%](PASTE_THE_IMAGE_URL_HERE)

Then write the slide content:

## [Lesson Title]

[The core claim. One sentence. Not a definition — a transferable insight the student can use tomorrow. Max 18 words.]

- **[Key term or concept]** — [One tight clause. Max 10 words.]
- **[Key term or concept]** — [One tight clause. Max 10 words.]
- **[Key term or concept]** — [One tight clause. Max 10 words.]
- **[Key term or concept]** — [One tight clause. Max 10 words.]

> **[Anchor: Example / Mental Model / The Rule]**
> [One sentence that makes the concept concrete and memorable. Real, specific, never vague.]

IMAGE RULES:
- ONLY use ![bg right:38%](url) when imageUrl is explicitly provided and non-null for that lesson
- The image directive must be the first line of the slide block, before ## heading
- Do NOT invent or guess image URLs — use exactly the url from the data
- If imageUrl is null, write the slide with no image directive at all

DIAGRAM RULE (use at most once per deck, only for a genuine A-vs-B comparison):
Replace the bullet list on ONE lesson slide with this HTML grid when the lesson genuinely compares two things:

<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px">
<div style="background:#F0FDF9;border-left:4px solid #00C896;padding:14px;border-radius:0 8px 8px 0">
<strong style="color:#00C896;font-size:10px;text-transform:uppercase;letter-spacing:2px">LABEL A</strong>
<p style="color:#334155;font-size:15px;margin:6px 0 0">One tight description. Max 12 words.</p>
</div>
<div style="background:#F5F3FF;border-left:4px solid #9B8FFF;padding:14px;border-radius:0 8px 8px 0">
<strong style="color:#9B8FFF;font-size:10px;text-transform:uppercase;letter-spacing:2px">LABEL B</strong>
<p style="color:#334155;font-size:15px;margin:6px 0 0">One tight description. Max 12 words.</p>
</div>
</div>

Still include the blockquote anchor below the diagram. Do not use the diagram and the image bg on the same slide.

═══════════════════════════════════════
DECK CLOSING SLIDE (one only):
═══════════════════════════════════════

SLIDE — BACK COVER
────────────────────
<!-- _class: backcover -->
<!-- _paginate: false -->

## [Course Title]

[One sentence: the transformation the student has made. Past tense. Specific.]

---

ai-bytes.org · © 2026 AI Bytes Learning

════════════════════════════════════════════════════════
COMPRESSION RULES — NON-NEGOTIABLE
════════════════════════════════════════════════════════

1. ONE slide per lesson. No anchor slide. No summary slide. No quiz slide. No exceptions.
2. Every bullet must be a **bold key term** followed by a dash and a tight clause. Never a full sentence bullet.
3. The anchor callout (blockquote) at the bottom of every lesson slide is mandatory — one sentence only.
4. No slide may repeat content from another slide. If it is on one slide, it is not on any other.
5. No filler: no "it is important to note", "in conclusion", "as we can see", "this will help you".
6. Numbers beat adjectives: "3 steps" not "several steps", "40% faster" not "much faster".
7. Lesson slide headings must match the lesson title exactly — do not rephrase.
8. The core claim sentence must make a specific assertion — not describe what the lesson is about.
9. Every bullet key term must be different — no synonyms, no repeats within a slide.
10. Total slide count = 1 cover + (1 divider per topic) + (1 per lesson) + 1 back cover. Nothing more.
11. Images: use ![bg right:38%](url) only when imageUrl is provided — paste the exact URL from the data.
12. Diagrams: use the HTML grid at most once per deck, only on a genuine comparison slide — never invent one gratuitously.
13. Never combine the image bg directive and the HTML diagram on the same slide.

Now generate the complete slide deck for the course described above.
Start immediately with the cover slide — no preamble.`;
}
